//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.372
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoliSoft.TVShowTracker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RoliSoft.TVShowTracker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Libraries used in this software:&lt;/p&gt;
        ///&lt;ul&gt;
        ///	&lt;li&gt;&lt;a href=&quot;http://system.data.sqlite.org/&quot;&gt;System.Data.SQLite&lt;/a&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;a href=&quot;http://htmlagilitypack.codeplex.com/&quot;&gt;Html Agility Pack&lt;/a&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;a href=&quot;http://json.codeplex.com/&quot;&gt;Json.NET&lt;/a&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;a href=&quot;http://www.xml-rpc.net/&quot;&gt;XML-RPC.NET&lt;/a&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;a href=&quot;http://www.nunit.org/&quot;&gt;NUnit&lt;/a&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;a href=&quot;http://code.msdn.microsoft.com/WindowsAPICodePack&quot;&gt;Windows® API Code Pack for Microsoft® .NET Framework&lt;/a&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;a  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AboutPage {
            get {
                return ResourceManager.GetString("AboutPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///	The TVShows table contains the name of the TV shows,
        ///	their ID and position when displayed by the software.
        ///*/
        ///CREATE TABLE tvshows (
        ///	rowid INTEGER,
        ///	showid INTEGER PRIMARY KEY,
        ///	name TEXT
        ///)
        ///
        ////*
        ///	The Episodes table contains all the episodes of all the
        ///	tracked TV shows with their associated Show ID.
        ///	The EpisodeId field is not random or auto incrementing,
        ///	it is calculated by concating Show ID with Season and Episode.
        ///	The AirDate field is a UNIX timestamp.
        ///	The Pic field contains an UR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DatabaseStructure {
            get {
                return ResourceManager.GetString("DatabaseStructure", resourceCulture);
            }
        }
    }
}
